# Dirs
data:
  base_root: "data"
  dirs:
    raw: "raw"
    references: "references"
    index: "hisat_index"
    trimmed: "trimmed"

output:
  base_root: "output"
  dirs:
    mapped: 'mapped'
    quantification: 'quantification'
    diff_analysis: 'differential_gene_expression_analysis'
    stat_plots: 'differential_gene_expression_analysis_plots'

qc:
  base_root: "QC"
  dirs:
    mapping: 'mapping'
    raw: 'raw'
    trimmed: 'trimmed'

workflow:
  base_root: "workflow"
  dirs:
    rules: "rules"
    scripts: "scripts"
    lib: "lib"

# Files
sra:
  - SRR11647685  # GSM4505876
  - SRR11647686  # GSM4505877
  - SRR11647687  # GSM4505878
  - SRR11647695  # GSM4505886
  - SRR11647696  # GSM4505887
  - SRR11647697  # GSM4505888

ref:
  annotation:
    link: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/gencode.v49.primary_assembly.annotation.gtf.gz"
    file_name: "gencode_annotation_v49.gtf"
  genome: 
    link: "https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_49/GRCh38.primary_assembly.genome.fa.gz"
    file_name: "homo_GRCh38_ref.fa"
  bed_annotation:
    link: "https://sourceforge.net/projects/rseqc/files/BED/Human_Homo_sapiens/hg38_GENCODE_V45_Basic.bed.gz"
    file_name: "hg38_GENCODE_V45.bed"
    

suffix:
  fasta: 'fasta'
  fastq: 'fastq'
  report: 'html'
  compress: 'gz'

qc_plots:
  deep-tools:
    - 'correlation'
    - 'pca'
  custom:
    - 'mapping_rates'
    - 'assigned_rates'
  rseqc:
    - 'all.geneBodyCoverage.curves'
    - 'all.clipping_profile.R1'
    - 'all.inner_distance_plot'
    - 'all.splice_junction'

analysis_results:
  diff_analysis:
    - 'normalized_counts_vst.csv'
    - 'GSEA_list.rnk'
    - 'DEG_stat_diff.csv'
    - 'DEG_biological_diff.csv'
    - 'vsd.rds'
    - 'dds.rds'
  plots:
    - 'DEG_stat.png'
    - 'DEG_biological.png'
    - 'volcano_plot.png'
    - 'MA_plot.png'
    - 'PCA_plot.png'

# States
paired_id:
  - 1
  - 2

# Program's params
fasterq_params:
  threads: 3

fastqc_params:
  threads: 3

hisat-build_params:
  threads: 6
  seed: 1
  prefix: 'hisat2_index'

mapping_qc_scripts:
    mapping_rates: workflow/scripts/plot_mapping_rates.py
    assigned_rates: 'workflow/scripts/map_assigned.r'
    aggregate_clipping: workflow/scripts/aggregate_clipping_profiles.r
    aggregate_inner: workflow/scripts/aggregate_inner_distance.r
    aggregate_splice: workflow/scripts/aggregate_junction_anntotation.r


analysis_scipts:
  diff_analysis: 'workflow/scripts/differential_gene_expression_analysis.R'
  deg_heat: 'workflow/scripts/plot_degs_heatmap.R'
  volcano:  'workflow/scripts/plot_volcano.R'
  ma_plot:  'workflow/scripts/plot_MA.R'
  pca_plot:  'workflow/scripts/plot_PCA.R'
