name: BDA-I

channels:
  - bioconda
  - conda-forge
  - defaults


dependencies:
  - python=3.12
  - snakemake>=9.13.7
  - sra-tools>=3.2.1
  - seqkit>=2.12.0
  - fastqc>=0.12
  - multiqc>=1.33
  - pigz>=2.8
  - hisat2>=2.2
  - samtools>=1.2
  - matplotlib>=3.10
  - deeptools>=3.5.6
  - rseqc>=5.0
  - cutadapt>=5.2
  - subread>=2.1.1
  - bioconductor-deseq2>=1.5
  - r-ggplot2>=4.0.0
  - r-pheatmap>=1.0.13
  - r-tidyverse>=2.0.0
  - bioconductor-apeglm>=1.32.0
  - r-ggrepel>=0.9.6